version: '3.8'

services:
  api:
    build: .
    container_name: hemoday_api
    env_file:
      - .env
    environment:
      # Указываем адрес нашего нового общего контейнера базы
      - POSTGRES_HOST=common_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hemoday
      - POSTGRES_USER=admin_me
      - POSTGRES_PASSWORD=RedStar-me
    volumes:
      - ./uploads:/app/uploads
      - ./migrations:/app/migrations
      - ./app:/app/app
    restart: always
    # Команда сама создаст таблицы в новой базе при старте
    command: sh -c "aerich upgrade && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.hemoday.rule=Host(`api.hemoday.online`)"
      - "traefik.http.routers.hemoday.entrypoints=websecure"
      - "traefik.http.routers.hemoday.tls.certresolver=myresolver"
      - "traefik.http.services.hemoday.loadbalancer.server.port=8000"

networks:
  web:
    external: true
